In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd

In [2]:
class LinearRegression:
    def __init__ (self,lr=0.001, itera=1000):
        self.lr = lr
        self.itera = itera
        self.w = None
        self.b = None
    def fit(self,X,Y):
        n_data , n_features =X.shape
        self.w = np.zeros(n_features)   
        self.b = 0
        for i in range (self.itera):
            Y_pred = np.dot(X,self.w) + self.b            
            loss = (1/n_data) * (Y_pred - Y)            
            dw = (1/n_data) * np.dot(X.T,loss)
            db = (1/n_data) * np.sum(loss)            
            self.w -= (self.lr * dw)
            self.b -= (self.lr * db)
        
    def predict(self,X):
        return (np.dot(X,self.w)+self.b)
    
    def mse(self,Y_act,Y_predi):
        return (np.mean((Y_act - Y_predi)**2))
        

In [3]:
df = pd.read_csv("/home/jarvis/python/regression_Dataset/Admission_Predict_Ver1.1.csv")

In [4]:
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [5]:
data = df.iloc[:,:].values


In [6]:
np.random.shuffle(data)
data[:5]

array([[ 77.  , 327.  , 112.  ,   3.  ,   3.  ,   3.  ,   8.72,   1.  ,
          0.74],
       [ 62.  , 307.  , 101.  ,   3.  ,   4.  ,   3.  ,   8.2 ,   0.  ,
          0.47],
       [  3.  , 316.  , 104.  ,   3.  ,   3.  ,   3.5 ,   8.  ,   1.  ,
          0.72],
       [381.  , 322.  , 104.  ,   3.  ,   3.5 ,   4.  ,   8.84,   1.  ,
          0.78],
       [225.  , 305.  , 105.  ,   2.  ,   3.  ,   2.  ,   8.23,   0.  ,
          0.67]])

In [7]:
n_trainData = data.shape[0] * 0.8
X_train = data[:int(n_trainData),:-1]
X_train.shape

(400, 8)

In [8]:
X_train[:5]

array([[ 77.  , 327.  , 112.  ,   3.  ,   3.  ,   3.  ,   8.72,   1.  ],
       [ 62.  , 307.  , 101.  ,   3.  ,   4.  ,   3.  ,   8.2 ,   0.  ],
       [  3.  , 316.  , 104.  ,   3.  ,   3.  ,   3.5 ,   8.  ,   1.  ],
       [381.  , 322.  , 104.  ,   3.  ,   3.5 ,   4.  ,   8.84,   1.  ],
       [225.  , 305.  , 105.  ,   2.  ,   3.  ,   2.  ,   8.23,   0.  ]])

In [9]:
X_test = data[int(n_trainData):,:-1]
X_test.shape

(100, 8)

In [10]:
X_test[:5]

array([[202.  , 315.  , 110.  ,   2.  ,   3.5 ,   3.  ,   8.46,   1.  ],
       [234.  , 304.  , 100.  ,   2.  ,   2.5 ,   3.5 ,   8.07,   0.  ],
       [372.  , 324.  , 110.  ,   3.  ,   3.5 ,   3.  ,   9.22,   1.  ],
       [117.  , 299.  , 102.  ,   3.  ,   4.  ,   3.5 ,   8.62,   0.  ],
       [216.  , 330.  , 116.  ,   5.  ,   5.  ,   4.5 ,   9.36,   1.  ]])

In [11]:
Y_train = data[:int(n_trainData),-1]
Y_train.shape

(400,)

In [12]:
Y_train[:5]

array([0.74, 0.47, 0.72, 0.78, 0.67])

In [13]:
Y_test = data[int(n_trainData):,-1]
Y_test.shape

(100,)

In [14]:
Y_test[:5]

array([0.72, 0.64, 0.89, 0.56, 0.93])

In [15]:
regression = LinearRegression()
regression.fit(X_train,Y_train)
Y_predicted = regression.predict(X_test)
# print(Y_predicted)
mse = regression.mse(Y_test,Y_predicted) 
print(mse)

0.014633940660431008
